name: NLP
channels:
  - conda-forge
  # - defaults
dependencies:
  - python
  # - pip
  # - pip:
  #   - ipython
  #   - pandas
  #   - tqdm
  #   - scikit-learn
  #   - scipy
  #   - matplotlib
  #   - nltk
  #   - plotly
  #   - numpy
  #   - nbformat
  #   - tensorflow

